const dates=[{date:'10月3日',weekday:'周五',title:'抵达 · 城市初见',place:'浅草 · 上野',distance:'约 8.6 km 步行'},{date:'10月4日',weekday:'周六',title:'古寺与巷弄',place:'谷中 · 秋叶原',distance:'约 6.2 km 步行'},{date:'10月5日',weekday:'周日',title:'海风与日落',place:'台场 · 银座',distance:'约 11.4 km 步行'},{date:'10月6日',weekday:'周一',title:'最后的咖啡',place:'代官山 · 惠比寿',distance:'约 4.8 km 步行'}];
const seed=[{id:1,date:0,time:'09:30',place:'成田机场',activity:'抵达东京 · 领取行李',route:'机场快线 Skyliner',duration:'约 70 分钟',notes:'提前准备好 eSIM 与 Suica',tag:'交通',color:'blue'},{id:2,date:0,time:'12:00',place:'浅草寺',activity:'雷门与仲见世通散步',route:'步行 12 分钟',duration:'约 1.5 小时',notes:'午餐：大黑家天妇罗',tag:'游玩',color:'orange'},{id:3,date:0,time:'15:30',place:'隅田公园',activity:'河畔看东京晴空塔',route:'步行 8 分钟',duration:'约 2 小时',notes:'日落时间 17:18',tag:'放空',color:'green'},{id:4,date:1,time:'10:00',place:'谷中银座',activity:'老街早餐与猫町散步',route:'地铁千代田线',duration:'约 2 小时',notes:'',tag:'美食',color:'orange'},{id:5,date:2,time:'14:00',place:'teamLab Borderless',activity:'沉浸式数字艺术展',route:'百合海鸥线',duration:'约 2.5 小时',notes:'门票已预约',tag:'体验',color:'purple'}];
let trips=JSON.parse(localStorage.getItem('tripbook-trips')||'null')||[];if(localStorage.getItem('tripbook-data-version')!=='2'){trips=[];localStorage.setItem('tripbook-data-version','2');localStorage.setItem('tripbook-trips','[]')}let activeDate=0;
const $=id=>document.getElementById(id); function save(){localStorage.setItem('tripbook-trips',JSON.stringify(trips))} function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function renderDates(){ $('dateStrip').innerHTML=dates.map((d,i)=>`<button class="date-card ${i===activeDate?'active':''}" data-date="${i}"><span class="weekday">${d.weekday}</span><strong>${d.date.replace('月',' / ').replace('日','')}</strong></button>`).join('');document.querySelectorAll('.date-card').forEach(b=>b.onclick=()=>{activeDate=+b.dataset.date;render()}) }
function render(){renderDates();const d=dates[activeDate];$('dayIndex').textContent=String(activeDate+1).padStart(2,'0');$('dayTitle').textContent=d.title;$('dayPlace').textContent=d.place;$('dayDistance').textContent=d.distance;const list=trips.filter(t=>t.date===activeDate).sort((a,b)=>a.time.localeCompare(b.time));$('timeline').innerHTML=list.map(t=>`<article class="timeline-item"><time class="time">${t.time}</time><span class="rail"></span><div class="item-body"><div class="item-top"><h3>${t.place}</h3><span class="tag">${t.tag||'行程'}</span></div><p class="item-sub"><i data-lucide="route"></i>${t.activity} <span>·</span> ${t.route||'自行前往'} <span>·</span> ${t.duration||'—'}</p>${t.notes?`<p class="item-note">${t.notes}</p>`:''}</div><button class="item-menu" data-edit="${t.id}" aria-label="编辑"><i data-lucide="more-horizontal"></i></button></article>`).join('');$('emptyState').style.display=list.length?'none':'flex';$('statCount').textContent=list.length;$('mapStops').textContent=`${list.length} 个地点`;$('statHours').textContent=list.length?`${(list.length*2.15).toFixed(1)}h`:'0h';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openForm(+b.dataset.edit));lucide.createIcons()}
function openForm(id=null){$('tripForm').reset();$('editId').value=id||'';$('modalTitle').textContent=id?'编辑行程':'添加行程';$('deleteBtn').style.visibility=id?'visible':'hidden';$('formDate').innerHTML=dates.map((d,i)=>`<option value="${i}">${d.date} · ${d.title}</option>`).join('');if(id){const t=trips.find(x=>x.id===id);Object.entries({formDate:t.date,formTime:t.time,formPlace:t.place,formActivity:t.activity,formRoute:t.route,formDuration:t.duration,formNotes:t.notes}).forEach(([k,v])=>$(k).value=v||'')}else $('formDate').value=activeDate;$('tripDialog').showModal()}
$('tripForm').onsubmit=e=>{e.preventDefault();const id=$('editId').value;const data={id:id?+id:Date.now(),date:+$('formDate').value,time:$('formTime').value,place:$('formPlace').value,activity:$('formActivity').value,route:$('formRoute').value,duration:$('formDuration').value,notes:$('formNotes').value,tag:'行程'};if(id)trips=trips.map(t=>t.id===+id?data:t);else trips.push(data);save();activeDate=data.date;$('tripDialog').close();render();toast(id?'行程已更新':'行程已添加')};$('deleteBtn').onclick=()=>{const id=+$('editId').value;if(id){trips=trips.filter(t=>t.id!==id);save();$('tripDialog').close();render();toast('行程已删除')}};$('addTop').onclick=()=>openForm();$('addEmpty').onclick=()=>openForm();$('shareBtn').onclick=()=>{navigator.clipboard?.writeText(location.href);toast('行程链接已复制')};$('editNote').onclick=()=>{const n=prompt('编辑旅途备忘',$('noteText').textContent);if(n!==null){$('noteText').textContent=n;toast('备忘已更新')}};render();lucide.createIcons();
let draftImages=[];
const oldOpenForm=openForm;
openForm=function(id=null){oldOpenForm(id);const t=id?trips.find(x=>x.id===id):null;draftImages=t?.images?[...t.images]:[];renderImagePreview()};
function renderImagePreview(){$('imagePreview').innerHTML=draftImages.map((src,i)=>`<span class="preview-wrap"><img src="${src}" alt="待保存图片"><button type="button" data-remove-image="${i}">×</button></span>`).join('');document.querySelectorAll('[data-remove-image]').forEach(b=>b.onclick=()=>{draftImages.splice(+b.dataset.removeImage,1);renderImagePreview()})}
$('formImages').onchange=async e=>{for(const file of e.target.files){if(!file.type.startsWith('image/'))continue;const src=await new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(file)});draftImages.push(src)}e.target.value='';renderImagePreview()};
const oldSubmit=$('tripForm').onsubmit;$('tripForm').onsubmit=e=>{e.preventDefault();const id=$('editId').value;const t=trips.find(x=>x.id===+id);const data={id:id?+id:Date.now(),date:+$('formDate').value,time:$('formTime').value,place:$('formPlace').value,activity:$('formActivity').value,route:$('formRoute').value,duration:$('formDuration').value,notes:$('formNotes').value,images:draftImages,tag:t?.tag||'行程'};if(id)trips=trips.map(x=>x.id===+id?data:x);else trips.push(data);save();activeDate=data.date;$('tripDialog').close();render();toast(id?'行程已更新':'行程已添加')};
const oldRender=render;render=function(){oldRender();document.querySelectorAll('[data-image]').forEach(i=>i.onclick=()=>window.open(i.dataset.image,'_blank'))};render();
